### ISSUE TITLE
[RE: JoSS Review] CS tag deconfliction

### ISSUE THREAD

**Issue by betteridiot** [akikuno/cstag#25]
For the JoSS review at openjournals/joss-reviews/issues/6066.

The `CS` (uppercase) is a reserved for color read sequence information as per the [SAM format](https://samtools.github.io/hts-specs/SAMtags.pdf), while the `cs` (lowercase)
tag represents the difference string. This has already been a [topic of discussion](https://github.com/samtools/samtools/issues/1030#issuecomment-477137623) while feature requests to incorporate the `cs` tag more 
formally into the SAM format.

It might be beneficial to change the "CS" to "cs" in all documentation so as to not mislead users.

**Comment by akikuno** [comment]
@betteridiot

Thank you very much for your invaluable review!

I have implemented the change to lowercase 'cs', as you pointed out, in both the paper and the GitHub documentation (README and Docstring).

JOSS Paper:

https://github.com/akikuno/cstag/commit/d7c6cfbad79b82ed1fa87d3a38e87e2c19768aaa

Document (README and Docstring):
https://github.com/akikuno/cstag/commit/20dec8d8d83d68f07fa13d1e89cfaf7cd5fe751d

I would appreciate your confirmation of these changes.

**Comment by betteridiot** [comment]
This satisfies my suggestion. Thank you.
