### ISSUE TITLE
paf input example?

### ISSUE THREAD

**Issue by dduchen** [akikuno/cstag#28]
Hello!
Thank you for your tool, I think it will be very useful for several applications I'm interested in. I was wondering how you might recommend using it to parse an alignment file containing cs tags (.paf) to obtain a VCF? 
Aside from concatenating all the read-level cs tags, and generating the vcf that way, is there an alternative approach you'd recommend?

Thank you again!

**Comment by akikuno** [comment]
Thank you for reaching out to me!

As the first and third columns of the PAF correspond to `chroms` and `positions`, I believe it can be parsed as follows:


```python
import cstag
from pathlib import Path

# Read the paf file as list[list[str]]
path_paf = Path("test.paf")
paf = [p.split("\t") for p in path_paf.read_text().splitlines()]

# Extract the chroms and positions
chroms = [p[0] for p in paf]
positions = [int(p[2]) for p in paf]

# Extract the cs tags
cs_tags = []
for record in paf:
    for tag in record:
        if tag.startswith("cs:Z:"):
            cs_tags.append(tag.replace("cs:Z:", ""))

print(cstag.to_vcf(cs_tags, chroms, positions))

```

If I have misunderstood any part of your requirements, please feel free to let me know.

**Comment by akikuno** [comment]
@dduchen

Hi, how is your issue going?
If you have any requirements or questions, please feel free to reach out to us.

**Comment by akikuno** [comment]
Closing this issue due to no contact since the last communication. 

@dduchen 

If you have any questions, please feel free to re-open this issue or create a new one.
